- src/clingwrapper.cxx
Following compiler-research/InterOp@0264bce
> Adapt to InterOp::GetFunctionSignature signature.

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
That would help us remove the crafty implementation of GetFunctionPrototype in InterOp.
> GetMethodPrototype is not used by cppyy. Mark it unused.

- clingwrapper/src/clingwrapper.cxx
This patch should help find the places where we should split the lookups into multiple unqualified ones.
> Throw an exception to signal where we still rely on qualified name lookups.

- .github/workflows/ci.yml
- CMakeLists.txt
- README.md
- python/cppyy_backend/loader.py
This patch builds a shared object which includes all necessary llvm symbols just like libcling did. That would pave our way to enable clang-repl based support in the cppyy-backend.
> Do not depend on libcling but solely on InterOp.

- clingwrapper/src/clingwrapper.cxx
This fixes the `Error in Interpreter::toString: the input *((std::string*)0x7fff8accec10) = cling::printValue((Dispatcher5*)0x56110fdad910); cannot be evaluated` errors
> Pass qualified name in ToString

- clingwrapper/src/clingwrapper.cxx
This resolves the issue https://github.com/compiler-research/cppyy-backend/issues/51 with the same title.
Parameters of the interpreter are read from the INTEROP_EXTRA_INTERPRETER_ARGS environment variable. If no arguments have been passed, the interpreter is created with -std=c++17 and -march=native.
> Allow passing custom arguments to CreateInterpreter

- python/cppyy_backend/loader.py
This fixes a subtle error when libcppyy-backend has all of its dependencies loaded and it exits successfully at the first time.
In that case python thinks that the cdll object is the error set and tries to iterate it causing a error:
```
Traceback (most recent call last):
File "/opt/conda/envs/.venv/lib/python3.10/site-packages/cppyy/__init__.py", line 80, in <module>
from ._cpython_cppyy import *
File "/opt/conda/envs/.venv/lib/python3.10/site-packages/cppyy/_cpython_cppyy.py", line 21, in <module>
c = loader.load_cpp_backend()
File "/home/jovyan/cppyy-backend/python/cppyy_backend/loader.py", line 99, in load_cpp_backend
c, err2 = _load_helper(name)
File "/opt/conda/envs/.venv/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
func = self._FuncPtr((name_or_ordinal, self)) …
```
> Return the error set.

- CMakeLists.txt
- clingwrapper/setup.py
- clingwrapper/src/clingwrapper.cxx
- python/cppyy_backend/loader.py
Add .dylib option when building on MacOS
Disabled use of -march=native when on Apple Silicon 
Link to CppInterOp (without this on MacOS you get undefined symbols error when building)
> Fixes issues that occur when building on Apple Silicon

- .github/workflows/ci.yml
- README.md
@vgvassilev This PR fixes a bug I introduced into the Ubuntu part of the CI with my last PR, which only showed by after merging, plus I update the build instructions in the README to match CppInterOp
> Update README.md + fix bug introduced into ci

- .github/workflows/ci.yml
@vgvassilev This PR removes redundant jobs from this ci. They're only there due to a copy and pasting of the ci from CppInterOp a while back. Can you merge?
> Remove redundant jobs from ci

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
This is part of the fix in `CPyCppyy/Dispatcher.cxx` where the old usages are replaced in favour of the canonical types.
> Add canonical type interface for method arguments

- .github/workflows/ci.yml
The valgrind CI commands were never updated to the new style on this repo and lags the other ones. It has been the same since llvm18 and 19, this now  fixes the two jobs that have been failing on master.
> [ci] Update the CI to follow other repositories in running valgrind

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
Fixes 5 previously failing test cases.
> fix: name conflict and `GetGlobalOperator`

- clingwrapper/src/clingwrapper.cxx
Fixes [`test03_replacement_of_eq`](https://github.com/Vipul-Cariappa/cppyy-compiler-research/blob/ee71db3b0e918ae1eaf89ccd5252d904b0f0d153/test/test_stltypes.py#L1092-L1093)
> fix parsing template params

- clingwrapper/src/clingwrapper.cxx
fixes 2 tests in cppyy
`test_doc_features.py::TestADVERTISED::test01_reduction_of_overloads` and `test_overloads.py::TestOVERLOADS::test02_class_based_overloads_explicit_resolution`
> fix `Cppyy::GetMethodSignature` to return list of argument type

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
This PR adds two interfaces required to sync CPyCppyy with upstream.
One interfaces is not implemented but is TBD for the numba extension. `GetNumBasesLongestBranch` has been implemented to handle a basic case but should also be extended
> Add longest inheritance path and arg match score interfaces

- .github/workflows/ci.yml
- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
Fixes `test_regression.py::TestREGRESSION::test31_enum_in_dir`
> implement `Cppyy::GetAllCppNames`

- clingwrapper/src/clingwrapper.cxx
11 new tests pass.
1 xfail, segfaults with this change.
> Update `Cppyy::GetScope` to handle nested namespaces and templates

- clingwrapper/src/clingwrapper.cxx
Since `Cpp::GetDatamembers` can potentially return `UsingShadowDecl` (compiler-research/CppInterOp#385), we will need to process datamembers through `GetUnderlyingScope`
---
To be merged after compiler-research/CppInterOp#385, but is safe to merge before.
> Accessing `Cpp::*` functions through `Cpp::GetUnderlyingScope`

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
Reference: https://github.com/compiler-research/CppInterOp/pull/394
> Implement `GetGlobalOperator`

- clingwrapper/src/clingwrapper.cxx
Enables `test_cpp11features.py::TestCPP11FEATURES::test10_optional`.
> `#include <optional>` if C++ version >= 17

- clingwrapper/src/clingwrapper.cxx
Fixes:
`test_datatypes.py::TestDATATYPES::test04_class_read_access` and `test_datatypes.py::TestDATATYPES::test05_class_data_write_access`
with https://github.com/compiler-research/CPyCppyy/pull/78
> fix: handle `std::byte` as a special case

- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu.yml
- .github/workflows/Windows.yml
- .github/workflows/emscripten.yml
- CMakeLists.txt
- README.md
Based on the change in CppInterOp: https://github.com/compiler-research/CppInterOp/pull/505 that prefixes the build option with `CPPINTEROP`
> Prefix InterOp cmake options

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
This allows CPyCppyy to no longer use index based interfaces to retrieve template method info. Deprecate `IsTemplatedConstructor`
> Add `GetTemplatedMethods` to simplify proxy creation

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
`GetMethodTemplate` now also checks for operators methods using `GetClassOperators`
`GetGlobalOperator` can now handle templated types
Fixes 2 tests. Along with https://github.com/compiler-research/CppInterOp/pull/509, fixes 3 tests.
> Improve operator resolution

- clingwrapper/src/clingwrapper.cxx
This is a POSIX only header, and should be included only on unix platforms
> clingwrapper - include dlfcn.h only on unix

- clingwrapper/src/clingwrapper.cxx
Hi @vgvassilev, the string parsing is required here. Because cppyy allows instantiation using strings. For example:
```python
In [1]: import cppyy
In [2]: from cppyy import gbl
In [3]: cppyy.cppdef("""
...: template<typename T, int N>
...: T add(T n) { return n + (T)N; }
...: """)
Out[3]: True
In [4]: gbl.add[int, 5](5)
Out[4]: 10
In [5]: gbl.add["int", "6"](5)
Out[5]: 11
In [6]: gbl.add["int, 7"](5)
Out[6]: 12
```
Enables 5 tests:
```txt
test_stltypes.py::TestSTLTUPLE::test01_tuple_creation_and_access
test_stltypes.py::TestSTLTUPLE::test03_tuple_iter
test_stltypes.py::TestSTLTUPLE::test04_tuple_lifeline
test_templates.py::TestTEMPLATES::test02_non_type_template_args
test_templates.py::TestTEMPLATES::test03_templated_function
```
> support template instantiation using integral values

- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
Depends on https://github.com/compiler-research/CppInterOp/pull/586 and https://github.com/compiler-research/CPyCppyy/pull/89.
Fixes 9 tests.
> implement `Cppyy::GetSmartPtrType` function

- clingwrapper/src/capi.h
- clingwrapper/src/clingwrapper.cxx
- clingwrapper/src/cpp_cppyy.h
Based on https://github.com/wlav/cppyy-backend/commit/240ea541a50ca54105b429f3665c76b8ae53e9f2, required for https://github.com/wlav/CPyCppyy/commit/c6d623a43f346b7703032df166fb2ca788456526 in CPyCppyy
> Add Cppyy::IsStaticTemplate, part of syncup with wlav/cppyy-backend

- clingwrapper/src/clingwrapper.cxx
resolving them yields `char`, but we want to treat them as `int`s therefore we treat them as special cases
---
fixes 1 test
> treat `int8_t` and `uint8_t` as special cases
